--DROP TABLE IF EXISTS books;
--DROP TABLE IF EXISTS users;
--DROP TABLE IF EXISTS orders;
--DROP TABLE IF EXISTS order_items;

CREATE TABLE IF NOT EXISTS books (
	id BIGSERIAL PRIMARY KEY,
	isbn VARCHAR(50) NOT NULL,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	pages INTEGER NOT NULL,
	cover BIGINT NOT NULL,
	price DECIMAL(6, 2) DEFAULT 0.0 NOT NULL,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	role BIGINT NOT NULL,
	deleted BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users,
    total_cost DECIMAL(6, 2) DEFAULT 0.0 NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT REFERENCES orders,
    book_id BIGINT REFERENCES books,
    quantity INTEGER NOT NULL,
    price DECIMAL(6, 2) DEFAULT 0.0 NOT NULL,
    deleted BOOLEAN DEFAULT false NOT NULL
);